type Course {
    id: String
    name: String
    description: String
    price: Int
    category: [String]
    sections: [Section]
}

type Section {
    name: String
    description: String
    module: [String]
}

type Query {
    fetchCourse: [Course]
    fetchSingleCourse(courseId: String): Course
}
