type Course {
    id: String
    name: String
    description: String
    price: Int
    category: [String]
}

type Query {
    fetchCourse: [Course]
    fetchSingleCourse(courseId: String!): Course
}
